iceberg: serialize snapshot removals individually
The Java implementation expects snapshot removal updates to be
serialized one at a time[1]. This meant that with Java REST catalogs, we
could trigger catalog-side errors like:

2025-02-10T19:09:53.865 WARN  [org.eclipse.jetty.server.HttpChannel] - /v1/namespaces/redpanda/tables/test
java.lang.IllegalArgumentException: Invalid set of snapshot ids to remove.
Expected one value but received: [2205058756266803285, 6389287107599228031, 837858603806954013, 8429544376017231169]
    at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkArgument(Preconditions.java:220)
    at org.apache.iceberg.MetadataUpdateParser.readRemoveSnapshots(MetadataUpdateParser.java:530)
    at org.apache.iceberg.MetadataUpdateParser.fromJson(MetadataUpdateParser.java:300)
    at org.apache.iceberg.rest.requests.UpdateTableRequestParser.lambda$fromJson$2(UpdateTableRequestParser.java:105)
    at java.base/java.lang.Iterable.forEach(Iterable.java:75)
    at org.apache.iceberg.rest.requests.UpdateTableRequestParser.fromJson(UpdateTableRequestParser.java:105)
    at org.apache.iceberg.rest.RESTSerializers$UpdateTableRequestDeserializer.deserialize(RESTSerializers.java:354)
    at org.apache.iceberg.rest.RESTSerializers$UpdateTableRequestDeserializer.deserialize(RESTSerializers.java:349)
    at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3785)
    at org.apache.iceberg.rest.RESTCatalogServlet$ServletRequestContext.from(RESTCatalogServlet.java:179)
    at org.apache.iceberg.rest.RESTCatalogServlet.doPost(RESTCatalogServlet.java:78)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:554)

This updates the snapshot removal action to return its removed snapshots
individually. Note that this doesn't mean there are multiple calls to
the catalog for removal, only that we serialize multiple lists each with
a single removal instead of a single list with multiple removals.

[1] https://github.com/apache/iceberg/blob/3e6da2e5437ffb3f643275927e5580cb9620256b/core/src/main/java/org/apache/iceberg/MetadataUpdateParser.java#L550-L553