test: adjust segment size in high throughput test
Fixes this. The test itself on some cloud tests is failing because the
test infrastructure is restricting the segment size

rptest.clients.rpk.RpkException: RpkException<Unexpected output,
expected 'topic-cesqbumulz\s+OK' got 'topic-cesqbumulz  INVALID_CONFIG:
segment size 16777216 is outside of allowed range [14680064, 14680064]'
on setting topic-cesqbumulz segment.bytes=16777216>

Signed-off-by: Noah Watkins <noahwatkins@gmail.com>