detailed_error: make copy constructible
std::expected<>::value() requires E to be copy-constructible so the
error can be copied into a bad_expected_access exception. operator*
doesn't have this check and asserts instead.